---

- name: Installation
  become: yes
  apt: name=nginx 
  
- name : Check démarrage
  become: yes
  service: name=nginx state=started enabled=true

- name: Supprimer default.conf
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: PHP
  become: yes
  include: php.yml

- name: configuration des sites
  become: yes
  include: site.yml
  with_items:
    - local.dev
    - demo.fr
